services:
  - type: web
    name: razberry-django-project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "razberry-django-project.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://razberry-django-project.onrender.com"
